const router = require("express").Router();

// imported the models
const UserModel = require("../models/User.model");

// bcryptjs import to encrypt user password
const bcryptjs = require("bcryptjs");

// /signup route to create a new user with email, password, and username
router.post("/signup", async (req, res) => {
  try {
    const foundUser = await UserModel.findOne({ email: req.body.email });
    if (foundUser) {
      res.status(403).json({ errorMessage: "Invalid credentials" });
    } else {
      const theSalt = bcryptjs.genSaltSync(12); // creates a salt generated by bcryptjs
      console.log("the salt: ", theSalt);
      // joins the users password and the salt to create a hashed password
      const hashedPassword = bcryptjs.hashSync(req.body.password, theSalt); 
      console.log({ hashedPassword, password: req.body.password });
      const createdUser = await UserModel.create({
        ...req.body,
        password: hashedPassword,
      });
      res.status(201).json(createdUser)
    }
  } catch (error) {
    console.log("User could not be created", error);
    res.status(500).json({ errorMessage: error });
  }
});

// route to /login an existing user
router.post('/login', async(req, res) => {
    try {
        const foundUser = await UserModel.findOne({email: req.body.email})
        if(!foundUser) {
            res.status(403).json({errorMessage: `Invalid credentials`})
        } else {
            // compares the users password they are trying to login with the hashed password stored in the DB
            const doesPasswordMatch = bcryptjs.compareSync(req.body.password, foundUser.password);
            if(!doesPasswordMatch) {
                res.status(403).json({errorMessage: `Invalid credentials`})
            } else {
                res.status(200).json({message: `You are now logged in!`})
            }
        }
    } catch (error) {
        
    }
})

module.exports = router;
