const router = require("express").Router();

// imported the models
const UserModel = require("../models/User.Model");

// bcryptjs import to encrypt user password
const bcryptjs = require("bcryptjs");

const jwt = require("jsonwebtoken");
const { isAuthenticated } = require("../middlewares/jwt.middleware");

// /signup route to create a new user with email, password, and username
router.post("/signup", async (req, res) => {
  try {
    const foundUser = await UserModel.findOne({ email: req.body.email });
    if (foundUser) {
      res.status(403).json({ errorMessage: "Invalid credentials" });
    } else {
      const theSalt = bcryptjs.genSaltSync(12); // creates a salt generated by bcryptjs
      console.log("the salt: ", theSalt);
      // joins the users password and the salt to create a hashed password
      const hashedPassword = bcryptjs.hashSync(req.body.password, theSalt);
      console.log({ hashedPassword, password: req.body.password });
      const createdUser = await UserModel.create({
        ...req.body,
        password: hashedPassword,
      });
      res.status(201).json(createdUser);
    }
  } catch (error) {
    console.log("User could not be created", error);
    res.status(500).json({ errorMessage: error });
  }
});

// route to /login an existing user
router.post("/login", async (req, res) => {
  try {
    const foundUser = await UserModel.findOne({ email: req.body.email });
    if (!foundUser) {
      res.status(403).json({ errorMessage: `Invalid credentials` });
    } else {
      // compares the users password they are trying to login with the hashed password stored in the DB
      const doesPasswordMatch = bcryptjs.compareSync(
        req.body.password,
        foundUser.password,
      );
      if (!doesPasswordMatch) {
        res.status(403).json({ errorMessage: `Invalid credentials` });
      } else {
        // setting up jwt (token for logged in session)
        const payload = { _id: foundUser._id };
        // creates the token that will be used on the frontend
        const authToken = jwt.sign(payload, process.env.TOKEN_SECRET, {
          algorithm: "HS256",
          expiresIn: "6h",
        });
        // need to add the authtoken to the response so we can grab it from the frontend
        res.status(200).json({ message: `You are now logged in!`, authToken });
      }
    }
  } catch (error) {}
});

// a route to verify the auth token
router.get("/verify", isAuthenticated, (req, res) => {
  res.status(200).json({ message: "Token is valid!", decodedToken: req.payload });
});

module.exports = router;
